apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-lfplxasa-stage
  namespace: tssc-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/go-lfplxasa/overlays/stage
    repoURL: https://github.com/xjiangorg/go-lfplxasa-gitops.git
    targetRevision: main
  destination:
    namespace: tssc-app-stage
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: tssc-gitops
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

